<?xml version = "1.0"?>
<robot name="sahabat_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ================================================== -->
<!-- Robot Parameters (edit these to match your robot)  -->
<!-- ================================================== -->

<!-- Wheel dimensions: 175mm diameter hoverboard wheels -->
<xacro:property name="wheel_radius" value="0.0875" />   <!-- 175mm / 2 = 87.5mm -->
<xacro:property name="wheel_width" value="0.057" />     <!-- Wheel width/thickness -->
<xacro:property name="wheel_base" value="0.33" />       <!-- Distance between wheels (center to center) -->

<!-- Caster wheel radius -->
<xacro:property name="caster_radius" value="0.03" />

<!-- Body dimensions -->
<xacro:property name="body_length" value="0.3" />
<xacro:property name="body_width" value="0.35" />
<xacro:property name="body_height" value="0.22" />

<!-- Camera arguments -->
<xacro:arg name="camera_name" default="zed2i" />
<xacro:arg name="camera_model" default="zed2i" />
<xacro:arg name="use_zed_localization" default="true" />

<!-- Include ZED camera macro -->
<xacro:include filename="$(find zed_wrapper)/urdf/zed_macro.urdf.xacro" />

<!--BASE LINK-->
<!-- base_link is at wheel axle height (wheel_radius above ground) -->

<link name = "base_link">

</link>

<!--BASEFOOTPRINT LINK-->
<!-- base_footprint is the ground projection of the robot (at Z=0) -->

<joint name="basefootprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 ${-wheel_radius}" rpy = "0 0 0"/>
</joint>

<link name="base_footprint">

</link>

<!--BODY LINK-->

<joint name = "body_joint" type = "fixed" >
    <parent link = "base_link"/>
    <child link = "body_link"/>
    <origin xyz = "-0.15 0 0" />
</joint>

<link name = "body_link">
    <visual>
        <origin xyz = "0.15 0 0.11" />
        <geometry>
            <box size = "${body_length} ${body_width} ${body_height}"/>
        </geometry>

        <material name = "blue"> 
            <color rgba = "0 0 1 1"/>
        </material>
    </visual>

    <collision>
        <origin xyz = "0.15 0 0.11" />
       <geometry>
            <box size = "${body_length} ${body_width} ${body_height}"/>
        </geometry>
    </collision>

    <inertial>
        <mass value = "5.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
</link>


<!--LEFT WHEEL-->
<!-- Wheels are at base_link height (Z=0), which is the axle height -->

<joint name = "left_wheel_joint" type = "continuous"> 

    <parent link= "base_link"/>
    <child link= "left_wheel_link"/>
    <origin xyz = "0 ${wheel_base/2} 0" rpy = "-1.571 3.142 0"/> 
    <axis xyz = "0 0 1"/>
    
</joint>

<link name = "left_wheel_link">
    <visual>
        <geometry>
            <cylinder length = "${wheel_width}" radius = "${wheel_radius}"/>
        </geometry>

        <material name = "black">
            <color rgba = "0 0 0 1"/>
        </material>
    </visual>

    <collision>
        <geometry>
            <cylinder length = "${wheel_width}" radius = "${wheel_radius}"/>
        </geometry>
    </collision>

    <inertial>
        <mass value = "3.0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial> 
</link>

<!--RIGHT WHEEL-->

<joint name = "right_wheel_joint" type = "continuous">

    <parent link = "base_link"/>
    <child link = "right_wheel_link"/>
    <origin xyz = "0 ${-wheel_base/2} 0" rpy = "1.571 0 0 "/> 
    <axis xyz = "0 0 -1"/>

</joint>

<link name = "right_wheel_link">

    <visual>
        <geometry>
            <cylinder length = "${wheel_width}" radius = "${wheel_radius}"/>
        </geometry>

        <material name = "black">
            <color rgba = "0 0 0 1"/>
        </material>
    </visual>

    <collision>
        <geometry>
            <cylinder length = "${wheel_width}" radius = "${wheel_radius}"/>
        </geometry>
    </collision>

    <inertial>
        <mass value = "3.0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial> 
</link>

<!-- FRONT CASTER WHEEL-->
<!-- Caster bottom should touch ground: Z = -(wheel_radius - caster_radius) -->

<link name = "front_caster_wheel_link" >
    <visual>
        <geometry>
            <sphere radius= "${caster_radius}"/>
        </geometry>

        <material name = "red" >
            <color rgba = "1 0 0 1"/>
        </material>
    </visual>

    <collision>
        <geometry>
            <sphere radius= "${caster_radius}"/>
        </geometry>
    </collision>

</link>

<joint name = "front_caster_wheel_joint" type="fixed">
    <parent link = "body_link"/>
    <child link = "front_caster_wheel_link"/>
    <origin xyz = "0.25 0 ${-(wheel_radius - caster_radius)}" /> 
</joint>


<!-- REAR CASTER WHEEL-->
<!-- Caster bottom should touch ground: Z = -(wheel_radius - caster_radius) -->

<link name = "rear_caster_wheel_link" >
    <visual>
        <geometry>
            <sphere radius= "${caster_radius}"/>
        </geometry>

        <material name = "purple" >
            <color rgba = "1 0 1 1"/>
        </material>
    </visual>

    <collision>
        <geometry>
            <sphere radius= "${caster_radius}"/>
        </geometry>
    </collision>
</link>

<joint name = "rear_caster_wheel_joint" type="fixed">
    <parent link = "body_link"/>
    <child link = "rear_caster_wheel_link"/>
    <origin xyz = "0.05 0 ${-(wheel_radius - caster_radius)}" /> 
</joint>

    <!-- LiDAR componenets-->

<joint name="lidar_joint" type="fixed">
    <parent link="body_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.15 0 0.25" rpy="0 0 0"/>
</joint>

<link name="lidar_link">
    <visual>
        <geometry>
            <cylinder radius="0.05" length="0.06"/>
        </geometry>
        <material name="Black">
            <color rgba="0 0 0 1"/>
        </material>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="0.05" length="0.06"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
</link>

</robot>