name: Default
revision: 1
waypoints:
- id: wp-1
  name: waypoint_1
  x: -1.094
  y: 0.692
  yaw: -2.439
  dwell_seconds: 0.0
  enabled: true
- id: wp-2
  name: waypoint_2
  x: -2.005
  y: 0.172
  yaw: -2.136
  dwell_seconds: 0.0
  enabled: true
- id: wp-3
  name: waypoint_3
  x: -3.004
  y: -1.902
  yaw: 0.88
  dwell_seconds: 0.0
  enabled: true
