from setuptools import find_packages, setup

package_name = 'shbat_pkg'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/urdf', [
            'urdf/sahabat_robot.urdf.xacro',
            'urdf/sahabat_robot_with_zed.urdf.xacro',
        ]),

        ('share/' + package_name + '/map', [
            'map/map_save.yaml',
            'map/map_save.pgm',
            'map/map_serial.data',
            'map/map_serial.posegraph'
        ]),
        
        ('share/' + package_name + '/launch', [
            'launch/sahabat_launch.py',
            'launch/sahabat_manual.launch.py',
            'launch/nav2_test_launch.py',
            'launch/slam_nav_launch.py',
            'launch/localization_patrol_launch.py',
            'launch/bringup.launch.py',
            'launch/navigation.launch.py',
            'launch/operations.launch.py',
            'launch/remote_operations.launch.py',
            'launch/waypoint_editor.launch.py',
        ]),
        ('share/' + package_name + '/launch/debug', [
            'launch/debug/basic_bringup.launch.py',
            'launch/debug/lidar_check.launch.py',
            'launch/debug/nav_odom_only.launch.py',
        ]),
        ('share/' + package_name + '/config', [
            'config/mapper_params_online_async.yaml',
            'config/localization__params_online_async.yaml',
            'config/nav2_params.yaml',
            'config/nav2_params_odom.yaml',
            'config/nav2_odom_only.yaml',
            'config/nav2_localization_overrides.yaml',
            'config/nav2_keepout_overrides.yaml',
            'config/zed_pos_tracking_override.yaml',
            'config/ekf.yaml',
            'config/amcl.yaml',
            'config/scan_filter.yaml',
            'config/patrol_waypoints.yaml',
            'config/slam_toolbox.yaml',
            'config/slam_toolbox_localization.yaml',
            'config/zed_depth_to_scan.yaml',
            'config/exhibit_routes.yaml',
            'config/collision_monitor_operator.yaml',
            'config/foxglove_operator.yaml',
        ]),
        ('share/' + package_name + '/behavior_trees', [
            'behavior_trees/navigate_to_pose_replan_if_path_invalid.xml',
        ]),
        ('share/' + package_name + '/rviz', [
            'rviz/nav2_test.rviz',
            'rviz/slam_nav.rviz',
            'rviz/waypoint_editor.rviz',
        ]),
 
    ],
    install_requires=[
        'setuptools',
        'pymodbus>=3.0.0',
        'numpy',
        'flask',
        'flask-cors',
        'pyserial',
    ],
    zip_safe=True,
    maintainer='sahabat',
    maintainer_email='sahabat@todo.todo',
    description='Sahabat robot ROS2 package with ZLAC8015D motor control',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'rpm_to_odom = shbat_pkg.rpm_to_odom:main',
            'kalman_filter = shbat_pkg.kalman_filter:main',
            'lidar_recovery = shbat_pkg.lidar_recovery:main',
            'lidar_control_panel = shbat_pkg.lidar_control_panel:main',
            'mapping_control_panel = shbat_pkg.mapping_control_panel:main',
            'joy2cmd = shbat_pkg.joy2cmd:main',
            'base_controller = shbat_pkg.base_controller:main',
            'test_motor = shbat_pkg.test_motor:main',
            'scan_filter = shbat_pkg.scan_filter:main',
            'waypoint_patrol = shbat_pkg.waypoint_patrol:main',
            'waypoint_collector = shbat_pkg.waypoint_collector:main',
            'waypoint_panel = shbat_pkg.waypoint_panel:main',
            'waypoint_manager = shbat_pkg.waypoint_manager:main',
            'api_bridge = shbat_pkg.api_bridge:main',
            'save_current_pose = shbat_pkg.save_current_pose:main',
            'pose_saver_auto = shbat_pkg.pose_saver_auto:main',
            'exhibit_navigator = shbat_pkg.exhibit_navigator:main',
            'operator_backend = shbat_pkg.operator_backend:main',
            'operator_mode_manager = shbat_pkg.operator_mode_manager:main',
            'slam_toolbox_initial_pose = shbat_pkg.slam_toolbox_initial_pose:main',
            'command_arbiter = shbat_pkg.command_arbiter:main',
            'mobile_gateway = shbat_pkg.mobile_gateway:main',
            'localization_recovery = shbat_pkg.localization_recovery:main',
            'dock_pose_initializer = shbat_pkg.dock_pose_initializer:main',
            'live_waypoint_editor = shbat_pkg.live_waypoint_editor:main',
            'continue_mapping_session = shbat_pkg.continue_mapping_session:main',
        ],
    },
)
